services:
  db_for_app:
    image: postgres:12.20-alpine3.20
    network_mode: bridge
    container_name: db_for_app
    volumes:
      - /home/arun/Documents/golang-db/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
      - POSTGRES_USER=$(POSTGRES_USER)
      - POSTGRES_DB=$(POSTGRES_DB)